#!/bin/bash

CUDA_VISIBLE_DEVICES=3 python train.py \
    --seed=123 \
    --experience_name="FontDiffuser_training_phase_2" \
    --data_root="data_examples" \
    --output_dir="result/FontDiffuser_phase2_double_scr_30w" \
    --report_to="tensorboard" \
    --phase_2 \
    --phase_1_ckpt_dir="/home/skc/FontDiffuser/weights/FontDiffuser_double/checkpoint-280000" \
    --scr_ckpt_path="/home/skc/FontDiffuser/outputs/scr_custom/scr_training/scr_300000.pth" \
    --sc_coefficient=0.01 \
    --num_neg=16 \
    --resolution=96 \
    --style_image_size=96 \
    --content_image_size=96 \
    --content_encoder_downsample_size=3 \
    --channel_attn=True \
    --content_start_channel=64 \
    --style_start_channel=64 \
    --train_batch_size=8 \
    --perceptual_coefficient=0.01 \
    --offset_coefficient=0.5 \
    --max_train_steps=30000 \
    --ckpt_interval=10000 \
    --gradient_accumulation_steps=1 \
    --log_interval=50 \
    --learning_rate=1e-5 \
    --lr_scheduler="constant" \
    --lr_warmup_steps=1000 \
    --drop_prob=0.1 \
    --mixed_precision="no" \
    --use_high_freq=True \
    --use_intelligent_fusion=True \
    --high_freq_fusion_type="adaptive" \
    --fusion_channel_reduction=16 \
    --fusion_spatial_kernel=7 \
    --fusion_cross_attn_heads=8 \
    --fusion_time_emb_dim=512 \
    --use_dis_loss=False \
    --dis_loss_weight=0.02 \
    --dis_preset=balanced \
    --dis_adaptive_weights=False \
    --dis_temperature=1.5 \
    --dis_erosion_kernel_size=2 \
    --dis_dilation_kernel_size=4 
    